### ISSUE TITLE
Practice 7 - camera_traffic_light_detector - code cmments

### ISSUE THREAD

**Issue by geopimik** [Karljohan99/autoware_mini_practice#11]
#### Comments
1. Assign first to local variables then check if is None
https://github.com/Karljohan99/autoware_mini_practice/blob/64eca9855dd21fe94985e867243abb2b8dce335a/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L125-L135

2. TrafficLightResultArray should be published continuously; if there are no traffic lights, it just needs to be an empty array. At the moment, you are publishing only when there are rois on the image.
https://github.com/Karljohan99/autoware_mini_practice/blob/64eca9855dd21fe94985e867243abb2b8dce335a/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L174

3. My personal preference: don't like this return at the very end of the callback and how the `self.publish_roi_images` is used 2 times very close by at the end. I would create `rois`, `classes` and `scores` somewhere at the beginning as empty lists and if there are `stoplines_on_path` they will be modified. Then the return can be omitted and `publish_roi_images` will be once
https://github.com/Karljohan99/autoware_mini_practice/blob/64eca9855dd21fe94985e867243abb2b8dce335a/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L174-L180

**Comment by geopimik** [comment]
Point 1. I see that it was given like that in the tutorial! But it is better to do it as suggested.

**Comment by Karljohan99** [comment]
Made all the suggested changes in 503603b

**Comment by geopimik** [comment]
Ok
