### ISSUE TITLE
Practice 3

### ISSUE THREAD

**Issue by geopimik** [Karljohan99/autoware_mini_practice#2]
Please correct:

1. You are looping over the waypoints two times. Reorganize it so it is done only once.
   - https://github.com/Karljohan99/autoware_mini_practice/blob/0e304677ffdcc33c2ce602527bca0446230851c4/practice_3/nodes/control/pure_pursuit_follower.py#L41
   - https://github.com/Karljohan99/autoware_mini_practice/blob/0e304677ffdcc33c2ce602527bca0446230851c4/practice_3/nodes/control/pure_pursuit_follower.py#L34
2. I would suggest assigning the following (see the code block below) together at the very end of the `path_callback`:
   - and before assigning, I would calculate `distance_to_velocity_interpolator` into the local variable.
   - Imagine there is a long path, and the `path_callback` would take 0.25 seconds to run. During that time, we have at least two cycles of `current_pose_callback`, and if we first update `path_linesting` and write it to the class variable, then we prepare `distance_to_velocity_interpolator` and assign it to the class variable, we can create a situation where in the `current_pose_callback` they are not in sync.
   - So preparing them into local variables and doing the assigning together and at the very end of the `path_callback` minimizes the risk of this happening

```
self.path_linestring = path_linestring
self.distance_to_velocity_interpolator = interp1d(distances, velocities, kind='linear')
```

Please answer: 

3. In [task 6](https://github.com/Karljohan99/autoware_mini_practice/tree/main/practice_3#instructions-4) in instructions point 4 `fill_value` and `bounds_error` are expected to be used. It shouldn't happen that we get distance out of the length limits of the path linestring when using shapely. But if it happens? What will [your code](https://github.com/Karljohan99/autoware_mini_practice/blob/0e304677ffdcc33c2ce602527bca0446230851c4/practice_3/nodes/control/pure_pursuit_follower.py#L49) currently do?

**Comment by Karljohan99** [comment]
3. Added `fill_value` and `bounds_error`. Without them, the interpolator could give a very large velocity value if the input distance is higher than the length limit. I also assume that if the distance is negative for some erroneous reason, we would get a negative velocity value from the interpolator.
