### ISSUE TITLE
Practice 4 - pure_pursuit_follower code

### ISSUE THREAD

**Issue by geopimik** [Karljohan99/autoware_mini_practice#4]
1. You are creating the `VehicleCmd` message twice, you could do it only once.

https://github.com/Karljohan99/autoware_mini_practice/blob/e44f89f3182ba5c0396eff1d5fb47b4cfaa99efe/practice_4/nodes/control/pure_pursuit_follower.py#L63-L100

Here You could use something like this. There will be a bit less code. Less code is less possible errors.

```
if
    steering_angle = 0
    velocity = 0
else
    # calculate the values
    steering_angle = 
    velocity = 

# Create VehicleCmd message and publish
    vehicle_cmd.ctrl_cmd.steering_angle = steering_angle
    vehicle_cmd.ctrl_cmd.linear_velocity = velocity
```

2. Similar "pattern" could be used also in `path_callback`. And in the if part we would set the local variables and the global variables will be assigned only in one place at the end of callback. And in critical places we could also add using the threading lock.

**Comment by Karljohan99** [comment]
Done in 9e09542

**Comment by geopimik** [comment]
OK
