### ISSUE TITLE
Practice 5 - points_clusterer

### ISSUE THREAD

**Issue by geopimik** [Karljohan99/autoware_mini_practice#5]
1. Task 3 point 4 says to add assert for checking if every point gets a label. It missing, please add.
2. Not sure if you got this error, but I got:

```
self.clusterer = DBSCAN(cluster_epsilon, cluster_min_size)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

```

**Comment by Karljohan99** [comment]
1. Done in 97fe8bd
2. I don't get that error, so I'm not sure what is causing that. Clearly only 2 arguments are given to the DBSCAN object.

**Comment by geopimik** [comment]
1. Please also add the node name to the message.
2. OK, I got rid of the error by making this line as follows.
```
self.clusterer = DBSCAN(eps=self.cluster_epsilon, min_samples=self.cluster_min_size)
```

**Comment by Karljohan99** [comment]
Both done in 9551524

**Comment by geopimik** [comment]
1. Better is to add node name using `rospy.get_name()` as here:
https://github.com/Karljohan99/autoware_mini_practice/blob/32ac8b4f6c64309b810fde34d169687b6a34e413/practice_5/nodes/planning/global/lanelet2_global_planner.py#L67

**Comment by Karljohan99** [comment]
Done in abe7dec

**Comment by geopimik** [comment]
OK
