### ISSUE TITLE
Practice_4 - lanelet2_global_planner - path is not ended

### ISSUE THREAD

**Issue by geopimik** [Karljohan99/autoware_mini_practice#6]
Found another issue with your solution. There is a simple fix for it! Currently you just forget to do something in your code!

Situation like this:
* the goal point is placed where the purple arrow is
* ego reaches the end of the path, but it is not cleared and no message that the goal has been reached is displayed in console

![image](https://github.com/Karljohan99/autoware_mini_practice/assets/33843059/0c7f8c9b-c688-43ed-8c75-9111fe5fec29)

**Comment by Karljohan99** [comment]
I now calculate distance to the goal based on the last waypoint on global path instead of the user placed goal point. (commit 7241322)

**Comment by geopimik** [comment]
Ok.

just an additional comment:

You create a new variable, last_waypoint, but you could use the same goal_point. You need to update the goal_point coordinates as you updated them in the case of last_waypoint. Then, you wouldn't need additional variables. There is no point in keeping the goal_point value as user input because it is not used anywhere. So after preparing the path, we could just update it with new coordinates (using the last waypoint from the path)
