### ISSUE TITLE
Practice 6 - simple_local_planner - the stopping point visualization is missing

### ISSUE THREAD

**Issue by geopimik** [Karljohan99/autoware_mini_practice#8]
There is no stopping point visualization, you should see the line before obstacle that dermines the stopping point, as in the image below.

![image](https://github.com/Karljohan99/autoware_mini_practice/assets/33843059/6f5a4b97-0af3-4fdb-ac72-efc2571c45d9)

When publishing local path you are missing the `stopping_point_distance`. More details in [task 5](https://github.com/Karljohan99/autoware_mini_practice/tree/main/practice_6#5-add-braking-safety-distance).

https://github.com/Karljohan99/autoware_mini_practice/blob/a09abb4acfa7dc931d7fc454a4906f6bcbae5884/practice_6/nodes/planning/local/simple_local_planner.py#L195

**Comment by Karljohan99** [comment]
Done in 00e500c

**Comment by geopimik** [comment]
Your calculation is wrong. It works with static obstacles, but not with dynamic ones. You shouldn't use `target_distances`.
https://github.com/Karljohan99/autoware_mini_practice/blob/64eca9855dd21fe94985e867243abb2b8dce335a/practice_6/nodes/planning/local/simple_local_planner.py#L191
This stopping wall should always be within extra braking distance before the obstacle.

**Comment by Karljohan99** [comment]
Should be fixed in 874c942

**Comment by geopimik** [comment]
ok
